apiVersion: infra.contrib.fluxcd.io/v1alpha1
  #apiVersion: tfcontroller.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: vault-pki-setup
  namespace: vault
spec:
  interval: 10m
  approvePlan: "auto"
  sourceRef:
    kind: GitRepository
    name: vault-config-repo 
  path: "./vault-config/terraform"
  env:
    - name: VAULT_TOKEN
      valueFrom:
        secretKeyRef:
          name: vault-root-token 
          key: token
    - name: VAULT_ADDR
      value: "http://vault.vault.svc.cluster.local:8200"
  dependsOn:
    - name: vault
      namespace: argocd
