apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Run after namespaces
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: vault-operator
    repoURL: https://bank-vaults.github.io/helm-charts
    targetRevision: 1.25.0
