apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraform-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Run after namespaces
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: tf-operator 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: flux2
    repoURL: https://fluxcd-community.github.io/helm-charts
    targetRevision: 2.13.0
    helm:
      values: |
        tfcontroller:
          create: true
        helmcontroller:
          create: false
        imageautomationcontroller:
          create: false
        imageReflectioncontroller:
          create: false
        kustomizecontroller:
          create: false
        notificationcontroller:
          create: false
        sourcecontroller:
          create: true
