apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3" # Run after vault-cluster is ready
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/huzlak/GME-manifests
    targetRevision: httpbin
    path: vault-config
